export const img={hero:'/activities/collaboration.jpg',coding:'/activities/coding.png',maker:'/activities/maker.png',ar:'/activities/ar.png',animation:'/activities/animation.png',anime:'/activities/anime.png',purpose:'/activities/sustainability.jpg',steamaker:'/klass/steamaker-cikal.webp',innovation:'/klass/innovation-gloria.webp',makerSet:'/klass/kryative-maker-set.webp',biotechnology:'/klass/biotechnology-xin-zhong.webp',codingKlass:'/klass/digitechnology-coding.webp',edubit:'/klass/digitechnology-edubit.webp',arStorytelling:'/klass/digitechnology-ar-storytelling.webp',digitalAnimation:'/klass/digital-animation.webp',animeDrawing:'/klass/anime-drawing.webp',visualThinking:'/klass/visual-thinking-chung-chung.webp'};
// Catalog verified at https://krya.global/academia/ on 2026-09-11.
// Display modes follow the current KRYAcademia catalog presentation.
export const klasses = [
  ['STEAMaker Upcycling Project', 'Onsite', 'Innovation & Creativity', '', img.steamaker, 'Explore everyday challenges through hands-on STEAM projects and upcycling.'],
  ['Innovation Klass', 'Onsite', 'Innovation & Creativity', '', img.innovation, 'Develop creative solutions to real-world problems through practical projects.'],
  ['Kryative Maker Set', 'Online', 'Innovation & Creativity', '', img.makerSet, 'Discover thematic STEAM activities with a hands-on learning kit.'],
  ['Biotechnology', 'Online', 'Technology', '', img.biotechnology, 'Connect everyday science with curiosity, teamwork, and environmental awareness.'],
  ['Digitechnology Coding Klass', 'Online', 'Technology', '', img.codingKlass, 'Create purposeful digital projects while developing coding and problem-solving skills.'],
  ['Digitechnology Krya x EDU:bit', 'Online', 'Technology', '', img.edubit, 'Explore coding, visual design, and three-dimensional game creation.'],
  ['Digitechnology AR Storytelling', 'Online', 'Technology', '', img.arStorytelling, 'Create augmented-reality stories that connect digital and physical worlds.'],
  ['Digital Animation', 'Online', 'Art & Language', '', img.digitalAnimation, 'Develop animation fundamentals through structured, creative practice.'],
  ['Anime Drawing', 'Onsite', 'Art & Language', '', img.animeDrawing, 'Draw characters and express original stories through anime-inspired art.'],
  ['Architecture and Interior', 'Online', 'Art & Language', '', img.visualThinking, 'Explore creativity and aesthetic awareness through visual and digital arts.'],
] as const;
export const programs=[['Holiday Program','Students · School break','Online / Onsite','/programs/holiday.webp','Creative project-based experiences that turn school holidays into meaningful time for discovery and making. Students explore a real-world theme, develop an original idea, build a practical outcome, and share what they learn with confidence.'],['Weekend Program','Students · Weekends','Online / Onsite','/programs/weekend.webp','Hands-on STEAM projects that build curiosity, teamwork, confidence, and practical skills at a comfortable weekend pace. Each session invites students to experiment, improve their ideas, and celebrate progress through a tangible project.'],['Extra–Intra Curricular','Schools · Students','At partner schools','/programs/extra-intra.webp','A school-developed learning program that enriches the curriculum through creativity, technology, and innovation. KRYAcademia works with the school to shape relevant themes, learning outcomes, schedules, and projects for its students.'],['Learning Journey','School groups','Onsite','/programs/learning-journey.webp','Field studies and guided experiences that connect classroom knowledge with real-world contexts. Students observe, ask questions, collect insights, and turn their discoveries into thoughtful reflections or collaborative project outcomes.']] as const;
export const updates = [
  ['Career', 'KRYAcademia is Hiring Creative Coaches to Inspire the Next Generation of Innovators', 'Join a team that helps young people learn through creativity, technology, and hands-on exploration.', '/updates/hiring.webp', 'https://krya.global/kryacademia-is-hiring-creative-coaches-to-inspire-the-next-generation-of-innovators/'],
  ['Holiday Program', 'Krya Online Holiday Program 2026: Creative Holiday Learning for Kids', 'A meaningful holiday program where children explore new ideas, make projects, and build confidence.', '/updates/holiday-program.webp', 'https://krya.global/krya-online-holiday-program-2026-creative-holiday-learning-for-kids/'],
  ['Krya News', 'Panduan Visual Paper KAN 2026: Syarat, Format, dan Jadwal Lengkap', 'Discover the requirements, format, and timeline for presenting a Visual Paper at KAN 2026.', '/updates/visual-paper.webp', 'https://krya.global/panduan-visual-paper-kan-2026-syarat-format-dan-jadwal-lengkap/'],
  ['Klass', 'Learning Physics Through Play with KRYAcademia Klass', 'See how science and physics become exciting hands-on learning experiences through play.', '/updates/physics.webp', 'https://krya.global/learning-physics-through-play-with-kryacademia-klass/'],
  ['Publication', 'New Publication by Krya: How AI Bioinformatics Empowers Young Learners to Innovate', 'Explore how biotechnology, AI, and real-world problem-solving help young learners build meaningful ideas.', '/updates/bioinformatics.webp', 'https://krya.global/new-publication-by-krya-how-ai-bioinformatics-empowers-young-learners-to-innovate/'],
  ['KAN 2026', 'Panggung Konferensi Anak Nasional (KAN) 2026 Menantimu!', 'A national stage where young innovators can share their ideas, projects, and voices.', '/updates/kan-stage.webp', 'https://krya.global/panggung-konferensi-anak-nasional-kan-2026-menantimu/'],
  ['Klass', 'Technova at SMP Dharma Mulya: Where Coding Meets Creativity', 'Technova Klass brings coding and innovation together through a hands-on school collaboration.', '/updates/technova.webp', 'https://krya.global/technova-at-smp-dharma-mulya-where-coding-meets-creativity/'],
  ['KAN 2026', 'Nominasi Kid Keynote Speaker Dibuka: Kesempatan Emas Anak Indonesia Tampil!', 'Children across Indonesia are invited to share their ideas as a Kid Keynote Speaker at KAN 2026.', '/updates/kid-keynote.webp', 'https://krya.global/nominasi-kid-keynote-speaker-dibuka-kesempatan-emas-anak-indonesia-tampil/'],
  ['KAN 2026', 'Konferensi Anak Nasional 2026: Rayakan Hari Anak bersama Krya Global', 'KAN 2026 creates a space for Indonesian children to present ideas, work, and meaningful perspectives.', '/updates/kan-2026.webp', 'https://krya.global/konferensi-anak-nasional-2026-rayakan-hari-anak-bersama-krya-global/'],
  ['Virtual Camp', 'The Future of Heritage: A Virtual Camp of Culture & Science Batch 2', 'A virtual learning journey connecting cultural heritage, science, exploration, and creativity.', '/updates/heritage-camp.webp', 'https://krya.global/the-future-of-heritage-a-virtual-camp-of-culture-science-batch-2/'],
] as const;
export const events=[['08','Young Makers Open Class','Open Class','Online','10:00–11:30 WIB','Register Now'],['14','Creative Technology Workshop','Workshop','Onsite','09:00–12:00 WIB','View Details'],['20','Student Ideas Exhibition','Exhibition','Hybrid','13:00–16:00 WIB','View Documentation'],['26','Schools Innovation Forum','Conference','Online','15:00–17:00 WIB','Registration Closed']] as const;
export const activities = [
  ['Hands-on learning with a KRYAcademia mentor', '/activities/collaboration.jpg'],
  ['Students exploring a project together', '/activities/learning-11.jpg'],
  ['Creative learning at KRYAcademia', '/activities/learning-33.jpg'],
  ['Students taking part in a KRYAcademia activity', '/activities/learning-12.jpg'],
  ['A shared learning experience', '/activities/learning-26.jpg'],
  ['Learning beyond the classroom', '/activities/learning-16.jpg'],
  ['Students working together at a computer', '/activities/sustainability.jpg'],
];
export const partners=['Elyon Christian School Surabaya','Xin Zhong School','SMA Negeri 5 Surabaya','Petra Christian School','Sampoerna Academy','Gloria Christian School','Dharma Mulya'];
// Original school logos from the official School Collaboration section, checked 2026-09-14.
export const partnerLogos = ['/partners/9.jpg', '/partners/4.jpg', '/partners/5.jpg', '/partners/92.png', '/partners/81.png', '/partners/6.jpg', '/partners/8.jpg'];
export const faqs=[['Who can join KRYAcademia?','Learning experiences are designed for elementary through high-school students, with the appropriate level varying by Klass or program.'],['Are learning experiences available online and onsite?','Online and onsite options vary by Klass. Please confirm your preferred mode and schedule with our team.'],['Where do onsite programs take place?','Locations vary by program and school partnership. The team confirms venue details before registration.'],['Can a school design a custom program?','Yes. We work with schools to shape programs around learning goals, age groups, schedules, and context.'],['How do I register for a Klass?','Choose the Klass you are interested in and send an inquiry. Our team will follow up with availability and guidance.'],['How can I contact the team?','Use the inquiry form, email aha@krya.global, or WhatsApp +62 851-1121-2362.']];
